In [1]:
import os, sys
sys.path.append("../")
# from classes.dataset import S3DIS1x1wIns
# import omegaconf

In [2]:
# cfg = omegaconf.OmegaConf.load("s3dis1x1.yaml")
# dataset_cfg = cfg.data
# dataset_cfg.dataroot = tp3d_dataset_path

In [3]:
from torch_points3d.datasets.segmentation.s3dis import read_s3dis_format

In [4]:
tp3d_dataset_file_path = "/mnt/sd1/torch_point3d/s3disfused/raw/Area_1/WC_1"

In [28]:
# dataset = S3DIS1x1Dataset(dataset_cfg)
torch_data = read_s3dis_format(tp3d_dataset_file_path, "WC_1")
torch_data

(tensor([[-16.7800,  42.6730,   2.7590],
         [-16.7330,  42.6900,   2.7580],
         [-16.7200,  42.6300,   2.7560],
         ...,
         [-17.0560,  43.8500,   1.5600],
         [-17.0720,  43.8540,   1.6010],
         [-17.0850,  43.8600,   1.6340]]),
 tensor([[160, 164, 193],
         [249, 255, 253],
         [244, 247, 254],
         ...,
         [135, 127,  91],
         [134, 129, 107],
         [137, 135, 110]], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 2, 2, 2]),
 tensor([35, 35, 35,  ..., 38, 38, 38]),
 tensor([5]))

In [21]:
from torchpcp.utils.io import ply
from torchpcp.utils.pytorch_tools import t2n

In [22]:
help(ply.write_pc)
help(ply.write_pc_label)
# ply.write_pc("raw_test.ply", t2n(torch_data[0]), t2n(torch_data[1]))
# ply.write_pc_label("ins_test.ply", t2n(torch_data[0]), t2n(torch_data[2]))

Help on function write_pc in module torchpcp.utils.io.ply:

write_pc(filename, xyz, rgb=None)
    write into a ply file
    ref.:https://github.com/loicland/superpoint_graph/blob/ssp%2Bspg/partition/provider.py

Help on function write_pc_label in module torchpcp.utils.io.ply:

write_pc_label(filename, xyz, labels, seed=0, color_map: list = None)



In [30]:
xyz = t2n(torch_data[0])
rgb = t2n(torch_data[1])
# xyz = torch_data[0]
# rgb = torch_data[1]


xyz_min = np.min(xyz, axis=0)
diff = 0 - xyz_min
normilized_xyz = xyz + diff

ply.write_pc("raw_normilized_test.ply", normilized_xyz, rgb)


In [13]:
npy_path = "/home/obarads/databox/torch_point3d/s3dis1x1ins/raw/scenes/Area_1_WC_1.npy"
npy_data = np.load(npy_path)
# npy_data.shape
npy_data



array([[4.053e+00, 4.400e-01, 2.163e+00, ..., 1.880e+02, 2.000e+00,
        0.000e+00],
       [4.033e+00, 4.380e-01, 2.163e+00, ..., 1.270e+02, 2.000e+00,
        0.000e+00],
       [4.043e+00, 6.580e-01, 2.580e-01, ..., 1.040e+02, 2.000e+00,
        0.000e+00],
       ...,
       [4.138e+00, 4.030e+00, 1.630e-01, ..., 1.040e+02, 2.000e+00,
        4.000e+01],
       [4.134e+00, 4.030e+00, 1.680e-01, ..., 1.050e+02, 2.000e+00,
        4.000e+01],
       [4.168e+00, 4.027e+00, 1.410e-01, ..., 1.020e+02, 2.000e+00,
        4.000e+01]])

In [17]:
# ply.write_pc("npy_raw_test.ply", npy_data[:, :3], npy_data[:, 3:6])
ply.write_pc_label("npy_sem_test.ply", npy_data[:, :3], npy_data[:, 6].astype(np.int32))
ply.write_pc_label("npy_ins_test.ply", npy_data[:, :3], npy_data[:, 7].astype(np.int32))


In [8]:
import k3d
import numpy as np

In [9]:
# get coords
coords = t2n(torch_data[0])
# get color codes
colors = t2n(torch_data[1])
colors = colors.astype(np.int32)
colors = colors[:, 0]*256*256 + colors[:,1]*256 + colors[:,2] # to color code

# visualize point cloud
plot = k3d.plot()
points = k3d.points(coords, colors.astype(np.float32), point_size=0.02, shader='flat')
plot += points
plot.display()


Output()

/home/obarads/anaconda3/envs/torch-points3dv2/lib/python3.7/site-packages/traittypes/traittypes.py:101: UserWarning: Given trait value dtype "float32" does not match required type "uint32". A coerced copy has been created.
  np.dtype(self.dtype).name))
